# Application Name
spring.application.name=MuseoConnect

# Server Port (Required for Railway)
server.port=${PORT:8080}


# MongoDB (Use Railway variable)
spring.data.mongodb.uri=${MONGO_URL}
spring.data.mongodb.auto-index-creation=true


jwt.secret=testsecret123456789012345678901234
jwt.expiration=3600000
#spring.data.mongodb.ssl.enabled=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Disable debug in production
spring.mail.properties.mail.debug=false